name: ci-pipeline for unit testing

on: 
    push:
        branches:
            main


jobs:
    ci-build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: Actions/checkout@v5

            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: 3.12

            - name: install dependencies
              run: pip install pytest


             

            - name: run pytest
              run: pytest -v 

            - name: printing the final test result
              run: echo "the uit test has been  completed successfully..!"

